# Generated by Django 5.2.5 on 2025-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_open_to_mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
