# Generated by Django 5.2.5 on 2025-09-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_college_profile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_open_to_mentoring',
        ),
    ]
