# Generated by Django 5.2.5 on 2025-09-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0007_remove_profile_is_open_to_mentoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution'),
        ),
    ]
